name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Hacer checkout del código
    - uses: actions/checkout@v4

    # Paso 2: Configurar JDK 23
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven

    # Paso 3: Listar archivos del proyecto (para depuración)
    - name: List project files
      run: ls -R

    # Paso 4: Construir con Maven 
    - name: Build with Maven
      run: mvn -B package -DskipTests --file UcoBet-Generales/pom.xml

    # Paso 5: Subir el artefacto generado
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: ucoBet-artifact
        path: UcoBet-Generales/target/*.jar
